require "nanoc3"

Dir['tasks/**/*.rake'].sort.each { |rakefile| load rakefile}

task :default => "site:build"

desc "Remove output files generated by nanoc3"
task :clean do
  system "rm -rf output"
end

