#!/usr/bin/env ruby

require "irb"
require File.join(File.dirname(__FILE__), "disqus")

API_KEY = "UePGFAkhiTbJELXX1CO1j1SpPoA59H61RT74xvlBa3OC1ErM755mjUbz7WxHtChg"
FORUM_ID = 293790

@blog = Disqus.new(API_KEY, FORUM_ID)

puts "Blog object is @blog"
puts @blog.inspect
IRB.start
