#!/usr/bin/env ruby

require "fileutils"
require "pathname"

include FileUtils

root = Pathname(File.join(File.dirname(__FILE__), ".."))
mkdir_p root + "logs"

exec %Q[/usr/local/sbin/nginx -p #{root}/ -c #{root}/nginx.conf \
-g "error_log #{root}/logs/nginx.error.log; pid #{root}/logs/nginx.pid;"]
